export const pedidos = [
  {
    id: 1,
    nome: 'Ana Lívia Remigio',
    email: 'livia.remigio@academico.ifpb.edu.br',
    itens: [
      { nome: 'Blusa branca', preco: 30.0 },
      { nome: 'Esmalte', preco: 15.9 },
      { nome: 'Prato', preco: 19.5 },
    ],
    numero: 102,
    data: '30/05/2025',
    valorTotal: 205.0,
    endereco: {
      cep: '58397-000 / Areia-PB',
      rua: 'Rua Padre Chacon',
      numero: '414',
      bairro: 'Bairro Frei Damião',
    },
    codigoRastreio: 'EX123456789BR',
    status: 'Em espera',
  },
  {
    id: 2,
    nome: 'Yago Jordas',
    email: 'yago@email.com',
    itens: [{ nome: 'Boné preto', preco: 15.0 }],
    numero: 162,
    data: '07/05/2025',
    valorTotal: 15.0,
    endereco: {
      cep: '58000-000 / João Pessoa-PB',
      rua: 'Rua das Palmeiras',
      numero: '200',
      bairro: 'Centro',
    },
    codigoRastreio: 'BR9988776655',
    status: 'Enviado',
  },
  {
    id: 3,
    nome: 'Luana de Almeida',
    email: 'luana@email.com',
    itens: [{ nome: 'bolsa', preco: 15.0 }],
    numero: 190,
    data: '07/09/2025',
    valorTotal: 15.0,
    endereco: {
      cep: '58000-000 / João Pessoa-PB',
      rua: 'Rua das Palmeiras',
      numero: '200',
      bairro: 'Centro',
    },
    codigoRastreio: 'BR9988736745',
    status: 'Em espera',
  },
];